[project]
name = "ai"
version = "0.1.0"
description = "AI to read microphone and identify speech and sounds for Godot game"
readme = "README.md"
authors = [
    { name = "MJMrigg", email = "riggmatthew20@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "whisper-mic>=1.4.4",
]

[project.scripts]
ai = "ai:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
